services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    volumes:
      - ./packages/frontend:/usr/app
      - /usr/app/node_modules
    container_name: leilao_em_foco_frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/usr/app
      - /usr/app/node_modules
    container_name: leilao_em_foco_backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/leilao?schema=public

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=leilao
    container_name: leilao_em_foco_db

volumes:
  postgres_data:
